name: state_management_presentation
description: "A new Flutter presentation about the state management in Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_deck: ^0.14.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_lints: ^3.0.2


flutter:
  uses-material-design: true
  assets:
    - assets/